### ISSUE TITLE
Can't get example to work

### ISSUE THREAD

**Issue by designbyadrian** [akzhy/gatsby-custom-md#10]
I'm running Gatsby 2.23.12.

The custom components aren't being parsed by gatsby-custom-md. Are there any required gatsby plugins I need to configure as well?

**Comment by akzhy** [comment]
Hey @designbyadrian there aren't any plugins that you need to configure. I haven't been updating the library for some time so changes in Gatsby may have caused the issue. I would recommend you try Mdx since **now** it does allow you to add markdown inside custom components.

**Comment by designbyadrian** [comment]
Thank you for your reply. I couldn't get this to work with MDX and was seeking alternatives. I understand your position and shall look deeper!

**Comment by designbyadrian** [comment]
Just for reference: I tried making MDX work with contentful, not that it matters much. Example markdown:

```mdx
<Column>![alt text](//image.gif)</Column>
```

Turns out for the MDX/JSX parser to understand there's markdown inside the component, I had to add blank lines without spaces:

```mdx
<Column>

![alt text](//image.gif)

</Column>
```

Source: https://github.com/mdx-js/mdx/issues/628#issuecomment-512885107

**Comment by akzhy** [comment]
@designbyadrian Glad you could make it work. Btw can you use mdx with contentful? Doesn't contentful have their own renderer?

**Comment by designbyadrian** [comment]
@akzhy Oh no, you just need `gatsby-source-contentful` and Gatsby will query contentful just like any other GraphQL source. Works perfectly!
